import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Create build directory if it doesn't exist
mkdirSync('build', { recursive: true });

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'build/main.js',
});

if (prod) {
	await context.rebuild();
	// Copy manifest.json to build directory
	copyFileSync('manifest.json', 'build/manifest.json');
	console.log('Copied manifest.json to build/');
	process.exit(0);
} else {
	// Copy manifest.json to build directory for dev mode too
	copyFileSync('manifest.json', 'build/manifest.json');
	console.log('Copied manifest.json to build/');
	await context.watch();
}
